# Generated by Django 5.2.3 on 2025-09-21 14:27

import datachoices.fields
import testapp.choices
import testapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DataChoiceArrayTestModel',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'materials',
                    datachoices.fields.DataChoiceArrayField(
                        choices=testapp.choices.MaterialChoices, size=None
                    ),
                ),
                (
                    'materials_default',
                    datachoices.fields.DataChoiceArrayField(
                        choices=testapp.choices.MaterialChoices,
                        default=testapp.models._materials_default,
                        size=None,
                    ),
                ),
                (
                    'materials_non_required',
                    datachoices.fields.DataChoiceArrayField(
                        blank=True,
                        choices=testapp.choices.MaterialChoices,
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='DataChoiceTestModel',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'shape',
                    datachoices.fields.DataChoiceField(
                        choices=testapp.choices.ShapeChoices
                    ),
                ),
                (
                    'shape_default',
                    datachoices.fields.DataChoiceField(
                        choices=testapp.choices.ShapeChoices, default='SQUARE'
                    ),
                ),
                (
                    'shape_non_required',
                    datachoices.fields.DataChoiceField(
                        blank=True, choices=testapp.choices.ShapeChoices, default=''
                    ),
                ),
            ],
        ),
    ]
