# Generated by Django 5.2.3 on 2025-09-11 13:02

import datachoices.fields
import testapp.choices
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'color',
                    models.CharField(
                        choices=[('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue')]
                    ),
                ),
                (
                    'shape',
                    datachoices.fields.DataChoiceField(
                        choices=testapp.choices.ShapeChoices
                    ),
                ),
                (
                    'materials',
                    datachoices.fields.DataChoiceArrayField(
                        choices=testapp.choices.MaterialChoices, size=None
                    ),
                ),
            ],
        ),
    ]
