name: main.yml
on: [push, pull_request]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: python tests/manage.py migrate
      - run: coverage run tests/manage.py test
